version: '3.9'

services:

    message-broker:
      image: rabbitmq:3-management-alpine 
      container_name: message-broker
      ports:
        - 5672:5672
        - 15672:15672
      volumes: 
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/mnesia
      networks: 
        - dev-network


    sender:
      container_name: sender
      ports:
        - 8080:8080
      build:
        context: .
        dockerfile: Dockerfile-sender
      environment:
        AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
      restart: always
      networks:
        - dev-network
      depends_on:
        - message-broker

    
    consumer:
      container_name: consumer
      build:
        context: .
        dockerfile: Dockerfile-consumer
      environment:
        AMQP_SERVER_URL: amqp://guest:guest@message-broker:5672/
      restart: always
      networks:
        - dev-network
      depends_on:
        - sender
        - message-broker

networks:
  dev-network:
    driver: bridge